name: pr

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: npm install
      - name: Bootstrap packages
        run: npm run bootstrap
      - name: Start docker
        run: docker-compose up --build -d
      - name: Execute test
        run: npm run test
      - name: Report to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Code Lint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: npm install
      - name: Execute lint
        run: npm run lint
